# Generated by Django 6.1 on 2026-09-10 08:36

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProConnectProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "sub",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, verbose_name="Sub ProConnect"
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True, db_index=True, max_length=14, verbose_name="SIRET"
                    ),
                ),
                (
                    "siren",
                    models.CharField(blank=True, db_index=True, max_length=9, verbose_name="SIREN"),
                ),
                (
                    "organization_label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom de l'organisation"
                    ),
                ),
                (
                    "roles",
                    models.JSONField(blank=True, default=list, verbose_name="Rôles ProConnect"),
                ),
                (
                    "raw_claims",
                    models.JSONField(blank=True, default=dict, verbose_name="Claims bruts OIDC"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proconnect_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil ProConnect",
                "verbose_name_plural": "Profils ProConnect",
            },
        ),
    ]
