# Generated by Django 6.1.1 on 2026-10-05 14:23

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proconnect", "0002_proconnectaccessconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicEntitySirene",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "siren",
                    models.CharField(
                        max_length=9, primary_key=True, serialize=False, verbose_name="SIREN"
                    ),
                ),
                (
                    "categorie_juridique",
                    models.CharField(
                        db_index=True, max_length=4, verbose_name="Catégorie Juridique"
                    ),
                ),
                (
                    "denomination",
                    models.CharField(blank=True, max_length=255, verbose_name="Dénomination"),
                ),
            ],
            options={
                "verbose_name": "Entité publique Sirene",
                "verbose_name_plural": "Entités publiques Sirene",
            },
        ),
    ]
