FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock ./

# Copy the application code
COPY . .

# Pre-install dependencies
RUN yarn install

EXPOSE 5173

ENTRYPOINT ["sh", "/app/scripts/frontend-entrypoint.sh"]
CMD ["dev"] 