FROM mcr.microsoft.com/playwright:v1.58.2-jammy

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn

# Install dependencies including playwright
RUN yarn install --immutable && yarn playwright install --with-deps

# Copy the rest of the application
COPY . .

# Default command
CMD ["yarn", "playwright", "test"]
