FROM node:20-alpine

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn

# Pre-install dependencies
RUN yarn install --immutable

EXPOSE 5173

ENTRYPOINT ["sh", "/app/scripts/frontend-entrypoint.sh"]
CMD ["dev"] 