# Generated by Django 5.2 on 2025-04-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signalements", "0002_signalement_pdf_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalement",
            name="concerne_une_entreprise",
            field=models.BooleanField(default=False, verbose_name="concerne une entreprise"),
        ),
        migrations.AddField(
            model_name="signalement",
            name="nom_entreprise",
            field=models.CharField(blank=True, max_length=255, verbose_name="nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name="signalement",
            name="nom_particulier",
            field=models.CharField(blank=True, max_length=255, verbose_name="nom du particulier"),
        ),
        migrations.AddField(
            model_name="signalement",
            name="numero_siret",
            field=models.CharField(blank=True, max_length=255, verbose_name="numéro SIRET"),
        ),
        migrations.AddField(
            model_name="signalement",
            name="prenom_particulier",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="prénom du particulier"
            ),
        ),
    ]
