# Generated by Django 5.2 on 2025-04-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signalements", "0003_signalement_concerne_une_entreprise_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signalement",
            name="concerne_une_entreprise",
        ),
        migrations.AddField(
            model_name="signalement",
            name="statut_auteur",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="statut de l'auteur"
            ),
        ),
    ]
