# Generated by Django 5.2 on 2025-04-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signalements", "0004_remove_signalement_concerne_une_entreprise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalement",
            name="risque_ecoulement",
            field=models.BooleanField(default=False, verbose_name="risque d'écoulement"),
        ),
    ]
