# Generated by Django 5.2.1 on 2025-05-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0005_signalement_risque_ecoulement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalement',
            name='pdf_document',
        ),
    ]
