# Generated by Django 5.2.1 on 2025-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0006_remove_signalement_pdf_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalement',
            old_name='document_generated_at',
            new_name='doc_constat_generated_at',
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='document',
        ),
        migrations.RemoveField(
            model_name='signalement',
            name='generate_doc',
        ),
        migrations.AddField(
            model_name='signalement',
            name='doc_constat',
            field=models.BinaryField(blank=True, null=True, verbose_name='Rapport de constatation'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='doc_constat_should_generate',
            field=models.BooleanField(default=False, help_text='Faut-il générer le rapport de constatation ?', verbose_name='Générer le rapport de constatation'),
        ),
    ]
