# Generated by Django 5.2.1 on 2025-06-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0007_renommer_doc_constat'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='lettre_info',
            field=models.BinaryField(blank=True, null=True, verbose_name="Lettre d'information"),
        ),
        migrations.AddField(
            model_name='signalement',
            name='lettre_info_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date lettre information'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='lettre_info_should_generate',
            field=models.BooleanField(default=False, help_text="Faut-il générer la lettre d'information ?", verbose_name="Générer la lettre d'information"),
        ),
    ]
