# Generated by Django 5.2.5 on 2025-09-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signalements", "0009_signalement_created_signalement_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signalement",
            name="nature_terrain",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="terrain"),
        ),
    ]
