# Generated by Django 5.2.5 on 2025-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signalements", "0011_fix_nature_terrain_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalement",
            name="accepte_accompagnement",
            field=models.BooleanField(default=False, verbose_name="accepte accompagnement"),
        ),
        migrations.AddField(
            model_name="signalement",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="email du contact"),
        ),
        migrations.AddField(
            model_name="signalement",
            name="contact_nom",
            field=models.CharField(blank=True, max_length=255, verbose_name="nom du contact"),
        ),
        migrations.AddField(
            model_name="signalement",
            name="contact_prenom",
            field=models.CharField(blank=True, max_length=255, verbose_name="prénom du contact"),
        ),
        migrations.AddField(
            model_name="signalement",
            name="contact_telephone",
            field=models.CharField(blank=True, max_length=20, verbose_name="téléphone du contact"),
        ),
    ]
