# Generated by Django 5.2.10 on 2026-01-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signalements", "0013_remove_signalement_souhaite_porter_plainte_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signalement",
            name="risque_ecoulement",
        ),
    ]
