# Generated by Django 5.2.10 on 2026-02-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signalements", "0015_remove_signalement_nom_entreprise_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Signalement",
        ),
    ]
