CHAMP_ID_TO_FIELD = {
    "Q2hhbXAtNTYxNzM1MQ==": "localisation_depot",
    "Q2hhbXAtNTYxNzM1Ng==": "nature_terrain",
    "Q2hhbXAtNTYxNzM1OA==": "auteur_signalement",
    "Q2hhbXAtNTYxNzM3MA==": "photo_dispo",
    "Q2hhbXAtNTYxNzM3Mg==": "risque_ecoulement",
    "Q2hhbXAtNTYxNzM3Mw==": "volume_depot",
    "Q2hhbXAtNTYxNzM3NQ==": "types_depot",
    "Q2hhbXAtNTYxNzM3Nw==": "precisions_depot",
    "Q2hhbXAtNTYxNzM4MQ==": "auteur_identifie",
    "Q2hhbXAtNTYxNzM4Mw==": "indices_disponibles",
    "Q2hhbXAtNTYxNzM4OQ==": "arrete_municipal_existe",
    "Q2hhbXAtNTgwMDExMQ==": "montant_forfait_enlevement",
    "Q2hhbXAtNTYxNzM5MA==": "prejudice_montant_connu",
    "Q2hhbXAtNTYxNzM5Mw==": "prejudice_nombre_personnes",
    "Q2hhbXAtNTYxNzM5NA==": "prejudice_nombre_heures",
    "Q2hhbXAtNTYxNzM5NQ==": "prejudice_nombre_vehicules",
    "Q2hhbXAtNTYxNzM5Nw==": "prejudice_kilometrage",
    "Q2hhbXAtNTYxNzQ3OA==": "prejudice_autres_couts",
    "Q2hhbXAtNTYxNzQ5MQ==": "nom_particulier",
    "Q2hhbXAtNTYxNzQ5Mg==": "prenom_particulier",
    "Q2hhbXAtNTYxNzQ5Mw==": "statut_auteur",
    "Q2hhbXAtNTYxNzQ4Mw==": "accepte_accompagnement",
    "Q2hhbXAtNTYxNzQ4NA==": "contact_telephone",
}

DATE_CONSTAT_CHAMP_ID = "Q2hhbXAtNTYxNzM2MQ=="  # Date et Heure de la constatation
