# Generated by Django 5.2.5 on 2025-11-21 10:27

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import backend.signalements.prejudice


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DNSignalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("commune", models.CharField(max_length=255, verbose_name="commune")),
                (
                    "localisation_depot",
                    models.CharField(blank=True, max_length=255, verbose_name="localisation"),
                ),
                ("date_constat", models.DateField(verbose_name="date de constatation")),
                ("heure_constat", models.TimeField(verbose_name="heure de constatation")),
                (
                    "auteur_signalement",
                    models.CharField(blank=True, max_length=255, verbose_name="auteur signalement"),
                ),
                (
                    "nature_terrain",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="terrain"),
                ),
                (
                    "volume_depot",
                    models.CharField(blank=True, max_length=255, verbose_name="volume"),
                ),
                (
                    "risque_ecoulement",
                    models.BooleanField(default=False, verbose_name="risque d'écoulement"),
                ),
                (
                    "types_depot",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="types"),
                ),
                ("precisions_depot", models.TextField(blank=True, verbose_name="précisions")),
                ("photo_dispo", models.BooleanField(default=False, verbose_name="photos")),
                (
                    "auteur_identifie",
                    models.BooleanField(default=False, verbose_name="auteur identifié"),
                ),
                (
                    "souhaite_porter_plainte",
                    models.BooleanField(default=False, verbose_name="souhaite porter plainte"),
                ),
                (
                    "indices_disponibles",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="indices"),
                ),
                (
                    "precisions_indices",
                    models.TextField(blank=True, verbose_name="précisions indices"),
                ),
                (
                    "arrete_municipal_existe",
                    models.BooleanField(default=False, verbose_name="arrêté municipal existe"),
                ),
                (
                    "montant_forfait_enlevement",
                    models.IntegerField(blank=True, null=True, verbose_name="forfait enlèvement"),
                ),
                (
                    "prejudice_montant_connu",
                    models.BooleanField(default=False, verbose_name="montant connu"),
                ),
                (
                    "prejudice_montant",
                    models.IntegerField(blank=True, null=True, verbose_name="montant préjudice"),
                ),
                (
                    "prejudice_nombre_personnes",
                    models.IntegerField(blank=True, null=True, verbose_name="personnes"),
                ),
                (
                    "prejudice_nombre_heures",
                    models.IntegerField(blank=True, null=True, verbose_name="heures"),
                ),
                (
                    "prejudice_nombre_vehicules",
                    models.IntegerField(blank=True, null=True, verbose_name="véhicules"),
                ),
                (
                    "prejudice_kilometrage",
                    models.IntegerField(blank=True, null=True, verbose_name="kilométrage"),
                ),
                (
                    "prejudice_autres_couts",
                    models.IntegerField(blank=True, null=True, verbose_name="autres coûts"),
                ),
                (
                    "prenom_particulier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="prénom du particulier"
                    ),
                ),
                (
                    "nom_particulier",
                    models.CharField(blank=True, max_length=255, verbose_name="nom du particulier"),
                ),
                (
                    "nom_entreprise",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="nom de l'entreprise"
                    ),
                ),
                (
                    "numero_siret",
                    models.CharField(blank=True, max_length=255, verbose_name="numéro SIRET"),
                ),
                (
                    "statut_auteur",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="statut de l'auteur"
                    ),
                ),
                (
                    "contact_nom",
                    models.CharField(blank=True, max_length=255, verbose_name="nom du contact"),
                ),
                (
                    "contact_prenom",
                    models.CharField(blank=True, max_length=255, verbose_name="prénom du contact"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email du contact"),
                ),
                (
                    "contact_telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="téléphone du contact"
                    ),
                ),
                (
                    "accepte_accompagnement",
                    models.BooleanField(default=False, verbose_name="accepte accompagnement"),
                ),
                (
                    "doc_constat",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Rapport de constatation"
                    ),
                ),
                (
                    "lettre_info",
                    models.BinaryField(blank=True, null=True, verbose_name="Lettre d'information"),
                ),
                (
                    "doc_constat_should_generate",
                    models.BooleanField(
                        default=False,
                        help_text="Faut-il générer le rapport de constatation ?",
                        verbose_name="Générer le rapport de constatation",
                    ),
                ),
                (
                    "doc_constat_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date rapport de constatation"
                    ),
                ),
                (
                    "lettre_info_should_generate",
                    models.BooleanField(
                        default=False,
                        help_text="Faut-il générer la lettre d'information ?",
                        verbose_name="Générer la lettre d'information",
                    ),
                ),
                (
                    "lettre_info_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date lettre information"
                    ),
                ),
                ("dn_numero_dossier", models.IntegerField(unique=True, verbose_name="numéro DN")),
                (
                    "dn_date_depot",
                    models.DateTimeField(blank=True, null=True, verbose_name="date de dépôt DN"),
                ),
                (
                    "dn_date_modification",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date modification DN"
                    ),
                ),
            ],
            options={
                "verbose_name": "signalement DN",
                "verbose_name_plural": "signalements DN",
            },
            bases=(backend.signalements.prejudice.PrejudiceMixin, models.Model),
        ),
    ]
