# Generated by Django 5.2.10 on 2026-01-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dnsignalement",
            old_name="auteur_signalement",
            new_name="constatant",
        ),
    ]
