# Generated by Django 5.2.10 on 2026-01-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0002_rename_auteur_signalement_to_constatant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dnsignalement",
            name="souhaite_porter_plainte",
        ),
        migrations.AlterField(
            model_name="dnsignalement",
            name="constatant",
            field=models.CharField(blank=True, max_length=255, verbose_name="constatant"),
        ),
    ]
