# Generated by Django 5.2.10 on 2026-01-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0003_remove_dnsignalement_souhaite_porter_plainte_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dnsignalement",
            name="risque_ecoulement",
        ),
    ]
