# Generated by Django 5.2.10 on 2026-01-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0004_remove_dnsignalement_risque_ecoulement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dnsignalement",
            name="nom_entreprise",
        ),
        migrations.RemoveField(
            model_name="dnsignalement",
            name="nom_particulier",
        ),
        migrations.RemoveField(
            model_name="dnsignalement",
            name="numero_siret",
        ),
        migrations.RemoveField(
            model_name="dnsignalement",
            name="prenom_particulier",
        ),
    ]
