# Generated by Django 5.2.10 on 2026-01-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0005_remove_dnsignalement_nom_entreprise_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dnsignalement",
            old_name="dn_date_depot",
            new_name="dn_date_creation",
        ),
        migrations.AlterField(
            model_name="dnsignalement",
            name="dn_date_creation",
            field=models.DateTimeField(blank=True, null=True, verbose_name="date de création DN"),
        ),
    ]
