# Generated by Django 5.2.11 on 2026-03-06 12:11

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0006_rename_dn_date_depot_to_creation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("numero_dossier", models.IntegerField(unique=True, verbose_name="numéro dossier")),
                (
                    "date_creation",
                    models.DateTimeField(blank=True, null=True, verbose_name="date de création"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "date_constat",
                    models.DateTimeField(blank=True, null=True, verbose_name="date de constat"),
                ),
                ("localisation_depot", models.TextField(blank=True, verbose_name="localisation")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossiers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "dossier",
                "verbose_name_plural": "dossiers",
            },
        ),
    ]
