# Generated by Django 4.2.16 on 2026-03-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0007_userdossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsignalement",
            name="auteur_adresse",
            field=models.TextField(blank=True, verbose_name="adresse de l'auteur"),
        ),
        migrations.AddField(
            model_name="dnsignalement",
            name="auteur_civilite",
            field=models.CharField(blank=True, max_length=20, verbose_name="civilité de l'auteur"),
        ),
        migrations.AddField(
            model_name="dnsignalement",
            name="auteur_nom",
            field=models.CharField(blank=True, max_length=255, verbose_name="nom de l'auteur"),
        ),
        migrations.AddField(
            model_name="dnsignalement",
            name="auteur_prenom",
            field=models.CharField(blank=True, max_length=255, verbose_name="prénom de l'auteur"),
        ),
        migrations.AddField(
            model_name="dnsignalement",
            name="auteur_siret",
            field=models.CharField(blank=True, max_length=14, verbose_name="SIRET de l'auteur"),
        ),
    ]
