# Generated by Django 4.2.16 on 2026-03-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0008_dnsignalement_auteur_adresse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsignalement",
            name="constatant_civilite",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="civilité du constatant"
            ),
        ),
        migrations.AddField(
            model_name="dnsignalement",
            name="constatant_nom",
            field=models.CharField(blank=True, max_length=255, verbose_name="nom du constatant"),
        ),
        migrations.AddField(
            model_name="dnsignalement",
            name="constatant_prenom",
            field=models.CharField(blank=True, max_length=255, verbose_name="prénom du constatant"),
        ),
        migrations.AlterField(
            model_name="dnsignalement",
            name="constatant",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="constatant (émetteur)"
            ),
        ),
    ]
