# Generated by Django 4.2.16 on 2026-03-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0009_dnsignalement_constatant_civilite_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dnsignalement",
            old_name="constatant",
            new_name="constatant_role",
        ),
        migrations.AlterField(
            model_name="dnsignalement",
            name="constatant_role",
            field=models.CharField(blank=True, max_length=255, verbose_name="rôle du constatant"),
        ),
    ]
