# Generated by Django 4.2.16 on 2026-03-31 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dn_signalements", "0010_rename_constatant_to_constatant_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsignalement",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dn_signalements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dnsignalement",
            name="commune",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="commune"),
        ),
        migrations.AlterField(
            model_name="dnsignalement",
            name="date_constat",
            field=models.DateField(blank=True, null=True, verbose_name="date de constatation"),
        ),
        migrations.AlterField(
            model_name="dnsignalement",
            name="heure_constat",
            field=models.TimeField(blank=True, null=True, verbose_name="heure de constatation"),
        ),
    ]
