# Generated by Django 4.2.16 on 2026-03-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0011_dnsignalement_user_alter_dnsignalement_commune_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserDossier",
        ),
    ]
