# Generated by Django 5.2.13 on 2026-06-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0012_delete_userdossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsignalement",
            name="entreprise_francaise",
            field=models.BooleanField(blank=True, null=True, verbose_name="entreprise française"),
        ),
    ]
