# Generated by Django 5.2.13 on 2026-06-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dn_signalements", "0013_dnsignalement_entreprise_francaise"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsignalement",
            name="ceci_est_un_test",
            field=models.BooleanField(blank=True, null=True, verbose_name="est un test"),
        ),
    ]
