# Generated by Django 5.2.13 on 2026-05-18 09:16

import backend.signalements.prejudice
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Constatation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("commune", models.CharField(max_length=255, verbose_name="commune")),
                ("localisation_depot", models.TextField(blank=True, verbose_name="localisation")),
                (
                    "date_constat",
                    models.DateField(blank=True, null=True, verbose_name="date de constatation"),
                ),
                (
                    "heure_constat",
                    models.TimeField(blank=True, null=True, verbose_name="heure de constatation"),
                ),
                (
                    "constatant_civilite",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="civilité du constatant"
                    ),
                ),
                (
                    "constatant_role",
                    models.CharField(blank=True, max_length=255, verbose_name="rôle du constatant"),
                ),
                (
                    "constatant_nom",
                    models.CharField(blank=True, max_length=255, verbose_name="nom du constatant"),
                ),
                (
                    "constatant_prenom",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="prénom du constatant"
                    ),
                ),
                (
                    "constatant_est_utilisateur_connecte",
                    models.BooleanField(
                        default=True, verbose_name="Le constatant est l'utilisateur connecté"
                    ),
                ),
                (
                    "nature_terrain",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="terrain"),
                ),
                (
                    "proprietaire_terrain_prive",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="propriétaire terrain privé"
                    ),
                ),
                (
                    "volume_depot",
                    models.CharField(blank=True, max_length=255, verbose_name="volume"),
                ),
                (
                    "types_depot",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="types"),
                ),
                ("precisions_depot", models.TextField(blank=True, verbose_name="précisions")),
                ("photo_dispo", models.BooleanField(default=False, verbose_name="photos")),
                (
                    "risque_ecoulement",
                    models.BooleanField(default=False, verbose_name="risque écoulement"),
                ),
                (
                    "auteur_identifie",
                    models.BooleanField(default=False, verbose_name="auteur présumé identifié"),
                ),
                (
                    "statut_auteur",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="statut de l'auteur présumé",
                    ),
                ),
                (
                    "auteur_civilite",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="civilité de l'auteur présumé"
                    ),
                ),
                (
                    "auteur_nom",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="nom de l'auteur présumé"
                    ),
                ),
                (
                    "auteur_prenom",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="prénom de l'auteur présumé"
                    ),
                ),
                (
                    "auteur_adresse",
                    models.TextField(blank=True, verbose_name="adresse de l'auteur présumé"),
                ),
                (
                    "auteur_siret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="siret de l'auteur présumé"
                    ),
                ),
                (
                    "entreprise_francaise",
                    models.BooleanField(blank=True, null=True, verbose_name="entreprise française"),
                ),
                (
                    "informations_auteur",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="informations auteur présumé",
                    ),
                ),
                (
                    "plainte_etat",
                    models.CharField(blank=True, max_length=255, verbose_name="état de la plainte"),
                ),
                (
                    "indices_disponibles",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="indices"),
                ),
                (
                    "precisions_indices",
                    models.TextField(blank=True, verbose_name="précisions indices"),
                ),
                (
                    "montant_forfait_enlevement",
                    models.IntegerField(blank=True, null=True, verbose_name="forfait enlèvement"),
                ),
                (
                    "prejudice_montant_connu",
                    models.BooleanField(default=False, verbose_name="montant connu"),
                ),
                (
                    "prejudice_montant",
                    models.IntegerField(blank=True, null=True, verbose_name="montant préjudice"),
                ),
                (
                    "prejudice_nombre_personnes",
                    models.IntegerField(blank=True, null=True, verbose_name="personnes"),
                ),
                (
                    "prejudice_nombre_heures",
                    models.IntegerField(blank=True, null=True, verbose_name="heures"),
                ),
                (
                    "prejudice_nombre_vehicules",
                    models.IntegerField(blank=True, null=True, verbose_name="véhicules"),
                ),
                (
                    "prejudice_kilometrage",
                    models.IntegerField(blank=True, null=True, verbose_name="kilométrage"),
                ),
                (
                    "prejudice_autres_couts",
                    models.IntegerField(blank=True, null=True, verbose_name="autres coûts"),
                ),
                (
                    "contact_nom",
                    models.CharField(blank=True, max_length=255, verbose_name="nom du contact"),
                ),
                (
                    "contact_prenom",
                    models.CharField(blank=True, max_length=255, verbose_name="prénom du contact"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email du contact"),
                ),
                (
                    "contact_telephone",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="téléphone du contact"
                    ),
                ),
                (
                    "accepte_accompagnement",
                    models.BooleanField(default=False, verbose_name="accepte accompagnement"),
                ),
                (
                    "ceci_est_un_test",
                    models.BooleanField(blank=True, null=True, verbose_name="est un test"),
                ),
                (
                    "doc_constat",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Rapport de constatation"
                    ),
                ),
                (
                    "lettre_info",
                    models.BinaryField(blank=True, null=True, verbose_name="Lettre d'information"),
                ),
                (
                    "doc_constat_should_generate",
                    models.BooleanField(
                        default=False, verbose_name="Générer le rapport de constatation"
                    ),
                ),
                (
                    "doc_constat_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date rapport de constatation"
                    ),
                ),
                (
                    "lettre_info_should_generate",
                    models.BooleanField(
                        default=False, verbose_name="Générer la lettre d'information"
                    ),
                ),
                (
                    "lettre_info_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date lettre information"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constatations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "constatation",
                "verbose_name_plural": "constatations",
            },
            bases=(backend.signalements.prejudice.PrejudiceMixin, models.Model),
        ),
    ]
