# Generated by hand

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constatations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constatation",
            name="prejudice_autres_couts",
            field=models.FloatField(blank=True, null=True, verbose_name="autres coûts"),
        ),
        migrations.AlterField(
            model_name="constatation",
            name="prejudice_kilometrage",
            field=models.FloatField(blank=True, null=True, verbose_name="kilométrage"),
        ),
        migrations.AlterField(
            model_name="constatation",
            name="prejudice_montant",
            field=models.FloatField(blank=True, null=True, verbose_name="montant préjudice"),
        ),
        migrations.AlterField(
            model_name="constatation",
            name="prejudice_nombre_heures",
            field=models.FloatField(blank=True, null=True, verbose_name="heures"),
        ),
        migrations.AlterField(
            model_name="constatation",
            name="prejudice_nombre_personnes",
            field=models.FloatField(blank=True, null=True, verbose_name="personnes"),
        ),
        migrations.AlterField(
            model_name="constatation",
            name="prejudice_nombre_vehicules",
            field=models.FloatField(blank=True, null=True, verbose_name="véhicules"),
        ),
    ]
