# Generated by Django 6.0.7 on 2026-08-06 14:27

from django.db import migrations, models


def set_existing_constatations_not_draft(apps, schema_editor):
    Constatation = apps.get_model("constatations", "Constatation")
    Constatation.objects.filter(is_draft=True).update(is_draft=False)


class Migration(migrations.Migration):

    dependencies = [
        ("constatations", "0003_calculate_prejudice_and_regenerate_docs"),
    ]

    operations = [
        migrations.AddField(
            model_name="constatation",
            name="is_draft",
            field=models.BooleanField(default=True, verbose_name="Est un brouillon"),
        ),
        migrations.RunPython(
            set_existing_constatations_not_draft,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

