# Generated by Django 6.0.7 on 2026-08-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constatations", "0005_alter_constatation_auteur_identifie"),
    ]

    operations = [
        migrations.AddField(
            model_name="constatation",
            name="photos",
            field=models.JSONField(blank=True, default=list, null=True, verbose_name="photos list"),
        ),
    ]
