# Generated by Django 6.0.7 on 2026-09-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constatations", "0006_constatation_photos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="constatation",
            old_name="accepte_accompagnement",
            new_name="accepte_traitement_donnees",
        ),
        migrations.AlterField(
            model_name="constatation",
            name="accepte_traitement_donnees",
            field=models.BooleanField(
                default=False, verbose_name="accepte le traitement des données"
            ),
        ),
        migrations.AddField(
            model_name="constatation",
            name="besoin_accompagnement",
            field=models.BooleanField(default=False, verbose_name="besoin d'accompagnement"),
        ),
    ]
