# Generated by Django 4.2.16 on 2026-04-22 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dn_signalements", "0012_delete_userdossier"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuiviProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "etape_en_cours",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Étape active"),
                ),
                (
                    "preuves_fournies",
                    models.BooleanField(default=False, verbose_name="Éléments de preuve joints"),
                ),
                (
                    "constatation_signee",
                    models.BooleanField(
                        default=False, verbose_name="Rapport de constatation signé"
                    ),
                ),
                (
                    "lettre_signe",
                    models.BooleanField(default=False, verbose_name="Lettre d'information signée"),
                ),
                (
                    "lettre_envoyee",
                    models.BooleanField(default=False, verbose_name="Lettre d'information envoyée"),
                ),
                (
                    "lettre_envoyee_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'envoi de la lettre"
                    ),
                ),
                (
                    "copie_archives",
                    models.BooleanField(default=False, verbose_name="Copie archivée"),
                ),
                (
                    "ar_recu",
                    models.BooleanField(default=False, verbose_name="Accusé de réception reçu"),
                ),
                (
                    "ar_statut",
                    models.CharField(blank=True, max_length=20, verbose_name="Statut de l'AR"),
                ),
                (
                    "ar_presentation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de présentation de l'AR"
                    ),
                ),
                (
                    "decision_poursuite",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Décision de poursuite"
                    ),
                ),
                ("montant_fixe", models.BooleanField(default=False, verbose_name="Montant fixé")),
                (
                    "montant_amende",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Montant de l'amende",
                    ),
                ),
                ("arrete_redige", models.BooleanField(default=False, verbose_name="Arrêté rédigé")),
                (
                    "titre_recette_emis",
                    models.BooleanField(default=False, verbose_name="Titre de recette émis"),
                ),
                (
                    "notification_sanction_envoyee",
                    models.BooleanField(
                        default=False, verbose_name="Notification de sanction envoyée"
                    ),
                ),
                (
                    "motif_abandon_choisi",
                    models.BooleanField(default=False, verbose_name="Motif d'abandon choisi"),
                ),
                (
                    "motif_abandon",
                    models.CharField(blank=True, max_length=255, verbose_name="Motif d'abandon"),
                ),
                (
                    "souhaite_notifier_abandon",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Souhaite notifier l'abandon"
                    ),
                ),
                (
                    "notification_abandon_envoyee",
                    models.BooleanField(
                        default=False, verbose_name="Notification d'abandon envoyée"
                    ),
                ),
                (
                    "nettoyage_fait",
                    models.BooleanField(blank=True, null=True, verbose_name="Nettoyage effectué"),
                ),
                (
                    "nettoyage_par",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nettoyage effectué par"
                    ),
                ),
                (
                    "observations_internes",
                    models.TextField(blank=True, verbose_name="Observations internes"),
                ),
                (
                    "date_recouvrement_effective",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de recouvrement effective"
                    ),
                ),
                (
                    "titre_recette_confirme",
                    models.BooleanField(default=False, verbose_name="Titre de recette confirmé"),
                ),
                (
                    "montant_recouvre",
                    models.BooleanField(default=False, verbose_name="Montant recouvré"),
                ),
                (
                    "dossier_archive",
                    models.BooleanField(default=False, verbose_name="Dossier archivé"),
                ),
                (
                    "signalement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suivi_procedure",
                        to="dn_signalements.dnsignalement",
                        verbose_name="Signalement lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi de procédure",
                "verbose_name_plural": "Suivis de procédures",
            },
        ),
    ]
