# Generated by Django 4.2.16 on 2026-04-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suiviprocedure",
            name="identification_reussie",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Identification de l'auteur réussie"
            ),
        ),
    ]
