# Generated by Django 4.2.16 on 2026-04-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0002_suiviprocedure_identification_reussie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suiviprocedure",
            name="motif_abandon_choisi",
        ),
    ]
