# Generated by Django 4.2.16 on 2026-05-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("constatations", "0001_initial"),
        ("procedures", "0003_remove_suiviprocedure_motif_abandon_choisi"),
    ]

    operations = [
        migrations.AddField(
            model_name="suiviprocedure",
            name="constatation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suivi_procedure",
                to="constatations.constatation",
                verbose_name="Constatation liée",
            ),
        ),
        migrations.AlterField(
            model_name="suiviprocedure",
            name="signalement",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Signalement lié",
            ),
        ),
    ]
