# Generated by Django 5.2.15 on 2026-06-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0004_suiviprocedure_constatation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suiviprocedure",
            name="signalement",
        ),
    ]
