# Generated by Django 6.0.6 on 2026-07-07 13:50

import django.db.models.deletion
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0005_remove_suiviprocedure_signalement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="suiviprocedure",
            name="date_assignation",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                monitor="personne_assignee",
                null=True,
                verbose_name="Date d'assignation",
            ),
        ),
        migrations.AddField(
            model_name="suiviprocedure",
            name="personne_assignee",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personne_assignee_suivi_procedures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigné à",
            ),
        ),
        migrations.AddField(
            model_name="suiviprocedure",
            name="statut_traitement",
            field=models.CharField(
                default="Nouveau", max_length=20, verbose_name="Statut de traitement"
            ),
        ),
    ]
