# Generated by Django 6.0.6 on 2026-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0006_suiviprocedure_assigned_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suiviprocedure",
            name="notes_traitement",
            field=models.TextField(blank=True, verbose_name="Notes de traitement"),
        ),
    ]
