# Generated by Django 6.1.1 on 2026-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0007_suiviprocedure_notes_traitement"),
    ]

    operations = [
        migrations.AddField(
            model_name="suiviprocedure",
            name="numero_suivi_lettre",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numéro de suivi du recommandé"
            ),
        ),
    ]
