# Generated by Django 6.0.7 on 2026-08-06 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
                ("action", models.CharField(blank=True, max_length=256, verbose_name="action")),
                ("actor", models.CharField(blank=True, max_length=256, verbose_name="actor")),
                ("object", models.CharField(blank=True, max_length=256, verbose_name="object")),
                ("target", models.CharField(blank=True, max_length=256, verbose_name="target")),
                (
                    "description",
                    models.TextField(blank=True, max_length=256, verbose_name="description"),
                ),
                (
                    "data",
                    models.JSONField(blank=True, max_length=256, null=True, verbose_name="data"),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Identifiant de session",
                    ),
                ),
                (
                    "constatation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="stats.statsconstatation",
                        verbose_name="Constatation liée",
                    ),
                ),
                (
                    "suivi_procedure",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="stats.statssuiviprocedure",
                        verbose_name="Suivi de procédure lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'activité",
                "verbose_name_plural": "Logs d'activités",
                "db_table": "stats_activity_log",
            },
        ),
    ]
