# Generated by Django 6.0.7 on 2026-08-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
                ("action", models.CharField(blank=True, max_length=256, verbose_name="action")),
                ("actor", models.CharField(blank=True, max_length=256, verbose_name="actor")),
                ("object", models.CharField(blank=True, max_length=256, verbose_name="object")),
                ("target", models.CharField(blank=True, max_length=256, verbose_name="target")),
                (
                    "description",
                    models.TextField(blank=True, max_length=256, verbose_name="description"),
                ),
                (
                    "data",
                    models.JSONField(blank=True, max_length=256, null=True, verbose_name="data"),
                ),
            ],
            options={
                "verbose_name": "Log d'activité",
                "verbose_name_plural": "Logs d'activités",
                "db_table": "stats_activity_log",
            },
        ),
    ]
