# Generated by Django 6.0.7 on 2026-07-23 15:51

import backend.constatations.prejudice
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatsConstatation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("commune", models.CharField(max_length=255, verbose_name="commune")),
                ("localisation_depot", models.TextField(blank=True, verbose_name="localisation")),
                (
                    "date_constat",
                    models.DateField(blank=True, null=True, verbose_name="date de constatation"),
                ),
                (
                    "heure_constat",
                    models.TimeField(blank=True, null=True, verbose_name="heure de constatation"),
                ),
                (
                    "constatant_civilite",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="civilité du constatant"
                    ),
                ),
                (
                    "constatant_role",
                    models.CharField(blank=True, max_length=255, verbose_name="rôle du constatant"),
                ),
                (
                    "constatant_nom",
                    models.CharField(blank=True, max_length=255, verbose_name="nom du constatant"),
                ),
                (
                    "constatant_prenom",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="prénom du constatant"
                    ),
                ),
                (
                    "constatant_est_utilisateur_connecte",
                    models.BooleanField(
                        default=True, verbose_name="Le constatant est l'utilisateur connecté"
                    ),
                ),
                (
                    "nature_terrain",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="terrain"),
                ),
                (
                    "proprietaire_terrain_prive",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="propriétaire terrain privé"
                    ),
                ),
                (
                    "volume_depot",
                    models.CharField(blank=True, max_length=255, verbose_name="volume"),
                ),
                (
                    "types_depot",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="types"),
                ),
                ("precisions_depot", models.TextField(blank=True, verbose_name="précisions")),
                ("photo_dispo", models.BooleanField(default=False, verbose_name="photos")),
                (
                    "risque_ecoulement",
                    models.BooleanField(default=False, verbose_name="risque écoulement"),
                ),
                (
                    "auteur_identifie",
                    models.BooleanField(default=False, verbose_name="auteur présumé identifié"),
                ),
                (
                    "statut_auteur",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="statut de l'auteur présumé",
                    ),
                ),
                (
                    "auteur_civilite",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="civilité de l'auteur présumé"
                    ),
                ),
                (
                    "auteur_nom",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="nom de l'auteur présumé"
                    ),
                ),
                (
                    "auteur_prenom",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="prénom de l'auteur présumé"
                    ),
                ),
                (
                    "auteur_adresse",
                    models.TextField(blank=True, verbose_name="adresse de l'auteur présumé"),
                ),
                (
                    "auteur_siret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="siret de l'auteur présumé"
                    ),
                ),
                (
                    "entreprise_francaise",
                    models.BooleanField(blank=True, null=True, verbose_name="entreprise française"),
                ),
                (
                    "informations_auteur",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="informations auteur présumé",
                    ),
                ),
                (
                    "plainte_etat",
                    models.CharField(blank=True, max_length=255, verbose_name="état de la plainte"),
                ),
                (
                    "indices_disponibles",
                    models.JSONField(blank=True, default=list, null=True, verbose_name="indices"),
                ),
                (
                    "precisions_indices",
                    models.TextField(blank=True, verbose_name="précisions indices"),
                ),
                (
                    "prejudice_montant_connu",
                    models.BooleanField(default=False, verbose_name="montant connu"),
                ),
                (
                    "prejudice_montant",
                    models.FloatField(blank=True, null=True, verbose_name="montant préjudice"),
                ),
                (
                    "prejudice_nombre_personnes",
                    models.FloatField(blank=True, null=True, verbose_name="personnes"),
                ),
                (
                    "prejudice_nombre_heures",
                    models.FloatField(blank=True, null=True, verbose_name="heures"),
                ),
                (
                    "prejudice_nombre_vehicules",
                    models.FloatField(blank=True, null=True, verbose_name="véhicules"),
                ),
                (
                    "prejudice_kilometrage",
                    models.FloatField(blank=True, null=True, verbose_name="kilométrage"),
                ),
                (
                    "prejudice_autres_couts",
                    models.FloatField(blank=True, null=True, verbose_name="autres coûts"),
                ),
                (
                    "contact_nom",
                    models.CharField(blank=True, max_length=255, verbose_name="nom du contact"),
                ),
                (
                    "contact_prenom",
                    models.CharField(blank=True, max_length=255, verbose_name="prénom du contact"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email du contact"),
                ),
                (
                    "contact_telephone",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="téléphone du contact"
                    ),
                ),
                (
                    "accepte_accompagnement",
                    models.BooleanField(default=False, verbose_name="accepte accompagnement"),
                ),
                (
                    "ceci_est_un_test",
                    models.BooleanField(blank=True, null=True, verbose_name="est un test"),
                ),
                (
                    "doc_constat_should_generate",
                    models.BooleanField(
                        default=False, verbose_name="Générer le rapport de constatation"
                    ),
                ),
                (
                    "doc_constat_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date rapport de constatation"
                    ),
                ),
                (
                    "lettre_info_should_generate",
                    models.BooleanField(
                        default=False, verbose_name="Générer la lettre d'information"
                    ),
                ),
                (
                    "lettre_info_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date lettre information"
                    ),
                ),
                (
                    "user_hash",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="hash utilisateur"
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique Constatation",
                "verbose_name_plural": "Statistiques Constatations",
                "db_table": "stats_constatation",
            },
            bases=(backend.constatations.prejudice.PrejudiceMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StatsSuiviProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "etape_en_cours",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Étape active"),
                ),
                (
                    "preuves_fournies",
                    models.BooleanField(default=False, verbose_name="Éléments de preuve joints"),
                ),
                (
                    "constatation_signee",
                    models.BooleanField(
                        default=False, verbose_name="Rapport de constatation signé"
                    ),
                ),
                (
                    "lettre_signe",
                    models.BooleanField(default=False, verbose_name="Lettre d'information signée"),
                ),
                (
                    "identification_reussie",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Identification de l'auteur réussie"
                    ),
                ),
                (
                    "lettre_envoyee",
                    models.BooleanField(default=False, verbose_name="Lettre d'information envoyée"),
                ),
                (
                    "lettre_envoyee_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'envoi de la lettre"
                    ),
                ),
                (
                    "copie_archives",
                    models.BooleanField(default=False, verbose_name="Copie archivée"),
                ),
                (
                    "ar_recu",
                    models.BooleanField(default=False, verbose_name="Accusé de réception reçu"),
                ),
                (
                    "ar_statut",
                    models.CharField(blank=True, max_length=20, verbose_name="Statut de l'AR"),
                ),
                (
                    "ar_presentation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de présentation de l'AR"
                    ),
                ),
                (
                    "decision_poursuite",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Décision de poursuite"
                    ),
                ),
                ("montant_fixe", models.BooleanField(default=False, verbose_name="Montant fixé")),
                (
                    "montant_amende",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Montant de l'amende",
                    ),
                ),
                ("arrete_redige", models.BooleanField(default=False, verbose_name="Arrêté rédigé")),
                (
                    "titre_recette_emis",
                    models.BooleanField(default=False, verbose_name="Titre de recette émis"),
                ),
                (
                    "notification_sanction_envoyee",
                    models.BooleanField(
                        default=False, verbose_name="Notification de sanction envoyée"
                    ),
                ),
                (
                    "motif_abandon",
                    models.CharField(blank=True, max_length=255, verbose_name="Motif d'abandon"),
                ),
                (
                    "souhaite_notifier_abandon",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Souhaite notifier l'abandon"
                    ),
                ),
                (
                    "notification_abandon_envoyee",
                    models.BooleanField(
                        default=False, verbose_name="Notification d'abandon envoyée"
                    ),
                ),
                (
                    "nettoyage_fait",
                    models.BooleanField(blank=True, null=True, verbose_name="Nettoyage effectué"),
                ),
                (
                    "nettoyage_par",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nettoyage effectué par"
                    ),
                ),
                (
                    "date_recouvrement_effective",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de recouvrement effective"
                    ),
                ),
                (
                    "titre_recette_confirme",
                    models.BooleanField(default=False, verbose_name="Titre de recette confirmé"),
                ),
                (
                    "montant_recouvre",
                    models.BooleanField(default=False, verbose_name="Montant recouvré"),
                ),
                (
                    "dossier_archive",
                    models.BooleanField(default=False, verbose_name="Dossier archivé"),
                ),
                (
                    "observations_internes",
                    models.TextField(blank=True, verbose_name="Observations internes"),
                ),
                (
                    "notes_traitement",
                    models.TextField(blank=True, verbose_name="Notes de traitement"),
                ),
                (
                    "statut_traitement",
                    models.CharField(
                        default="Nouveau", max_length=20, verbose_name="Statut de traitement"
                    ),
                ),
                (
                    "date_pilotage",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de pilotage"),
                ),
                ("personne_assignee_id", models.IntegerField(blank=True, null=True)),
                (
                    "constatation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suivi_procedure",
                        to="stats.statsconstatation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistique Suivi de procédure",
                "verbose_name_plural": "Statistiques Suivis de procédures",
                "db_table": "stats_suivi_procedure",
            },
        ),
    ]
