# Generated by Django 6.0.7 on 2026-08-06 14:27

from django.db import migrations, models


def set_existing_stats_not_draft(apps, schema_editor):
    StatsConstatation = apps.get_model("stats", "StatsConstatation")
    StatsConstatation.objects.filter(is_draft=True).update(is_draft=False)


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statsconstatation",
            name="is_draft",
            field=models.BooleanField(default=True, verbose_name="Est un brouillon"),
        ),
        migrations.RunPython(
            set_existing_stats_not_draft,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

