# Generated by Django 6.0.7 on 2026-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_statsconstatation_is_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statsconstatation",
            name="auteur_identifie",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="auteur présumé identifié"
            ),
        ),
    ]
