# Generated by Django 6.1 on 2026-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_statsconstatation_photos"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("matomo", "Matomo"),
                            ("tally", "Tally"),
                            ("rdv", "RDV Service Public"),
                        ],
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                ("metric", models.CharField(max_length=64, verbose_name="métrique")),
                ("date", models.DateField(verbose_name="jour")),
                (
                    "dimension",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="modalité"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="valeur"),
                ),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="détails")),
                ("collected_at", models.DateTimeField(auto_now=True, verbose_name="collecté le")),
            ],
            options={
                "verbose_name": "Métrique externe",
                "verbose_name_plural": "Métriques externes",
                "db_table": "stats_external_metric",
                "indexes": [
                    models.Index(
                        fields=["source", "metric", "date"], name="external_metric_lookup_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "metric", "date", "dimension"),
                        name="unique_external_metric",
                    )
                ],
            },
        ),
    ]
